module.exports = {
  DB_NAME: 'cozy-places',
  SESSION_KEY: 'I HATE APIS WHY IS NOT EASIER??',
/*   client_id: 'XZEXKQCKR5BTM4P3WDXCLMHXMZAIWDURILERHPCM0M4ZZ4LD',
  client_secret: 'O0DVKVU02U4OU3PSMD25PU13SFOYDC1R0ZYOHFM4DQIB4TJQ' */
  client_id: 'VLHOZSCEVHIBF2LRATBWBEDIVIS0IXNIBNF3SROZ4KEUNTWZ',
  client_secret: 'DCOZT2HC0AKHUKY4V1LB5CREKRUFAV512VATLOCJBMBOQRDP'  
/*   client_id: 'L3BM2ANUAFAAD1A3Z0AAXW5BBRTRUHRW4IWYBM2NZBFVFL4E',
  client_secret: '05FJRU2RUTOGNBJOHLXCYTRFAZUJFLHF0S1RYWB2WHVD4BJD' */
}


