module.exports = {
/*   client_id: 'XZEXKQCKR5BTM4P3WDXCLMHXMZAIWDURILERHPCM0M4ZZ4LD',
  client_secret: 'O0DVKVU02U4OU3PSMD25PU13SFOYDC1R0ZYOHFM4DQIB4TJQ' */
/*   client_id: 'VLHOZSCEVHIBF2LRATBWBEDIVIS0IXNIBNF3SROZ4KEUNTWZ',
  client_secret: 'DCOZT2HC0AKHUKY4V1LB5CREKRUFAV512VATLOCJBMBOQRDP'  */ 

}


